export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  WORKSPACE: '/workspace',
  MY_WORK: '/my-work',
  REVIEWS: '/reviews',
  USERS: '/users',
  USER_CREATE: '/users/create',
  USER_EDIT: (id) => `/users/${id}/edit`,
  USER_DETAILS: (id) => `/users/${id}`,
  ROLES: '/roles',
  ROLE_CREATE: '/roles/create',
  ROLE_EDIT: (id) => `/roles/${id}/edit`,
  ROLE_PERMISSIONS: (id) => `/roles/${id}/permissions`,
  PERMISSIONS: '/permissions',
  SETTINGS: '/settings',
  AUDIT_LOGS: '/audit-logs',
  PLATFORMS: '/platforms',
  PLATFORM_CREATE: '/platforms/create',
  PLATFORM_EDIT: (id) => `/platforms/${id}/edit`,
  BOARDS: '/boards',
  BOARD_CREATE: '/boards/create',
  BOARD_EDIT: (id) => `/boards/${id}/edit`,
  BOARD_DETAILS: (id) => `/boards/${id}`,
  CAMPAIGNS: '/campaigns',
  CAMPAIGN_CREATE: '/campaigns/create',
  CAMPAIGN_EDIT: (id) => `/campaigns/${id}/edit`,
  CAMPAIGN_DETAILS: (id) => `/campaigns/${id}`,
  TEAMS: '/teams',
  TEAM_CREATE: '/teams/create',
  TEAM_EDIT: (id) => `/teams/${id}/edit`,
  TEAM_DETAILS: (id) => `/teams/${id}`,
  TASK_TYPES: '/task-types',
  TASK_TYPE_CREATE: '/task-types/create',
  TASK_TYPE_EDIT: (id) => `/task-types/${id}/edit`,
  POST_LINKS: '/post-links',
  POST_LINK_CREATE: '/post-links/create',
  POST_LINK_EDIT: (id) => `/post-links/${id}/edit`,
  POST_LINK_DETAILS: (id) => `/post-links/${id}`,
  TASKS: '/tasks',
  TASK_CREATE: '/tasks/create',
  TASK_EDIT: (id) => `/tasks/${id}/edit`,
  TASK_DETAILS: (id) => `/tasks/${id}`,
  ASSIGNMENTS: '/assignments',
  ASSIGNMENT_DETAILS: (id) => `/assignments/${id}`,
  COMMENT_SUGGESTIONS: '/comment-suggestions',
  COMMENT_SUGGESTION_CREATE: '/comment-suggestions/create',
  COMMENT_SUGGESTION_EDIT: (id) => `/comment-suggestions/${id}/edit`,
  PROOFS: '/proofs',
  PROOF_DETAILS: (id) => `/proofs/${id}`,
  REPORTS: '/reports',
  REPORTS_CAMPAIGNS: '/reports/campaigns',
  REPORTS_TEAMS: '/reports/teams',
  REPORTS_MEMBERS: '/reports/members',
  REPORTS_TASKS: '/reports/tasks',
  REPORTS_ACTIVITY: '/reports/activity',
  NOTIFICATIONS: '/notifications',
  QUICK_START: '/quick-start',
  USAGE_GUIDE: '/guide',
  FORBIDDEN: '/403',
};
